import blogImg1 from '../assets/Planks with the horizon in the distance _ Free Photo_files/close-up-view-seashells-sand_23-2147646980.jpg';
import blogImg2 from '../assets/Planks with the horizon in the distance _ Free Photo_files/compass-mollusks-blue-background_23-2147621922.jpg';
import blogImg3 from '../assets/Planks with the horizon in the distance _ Free Photo_files/top-view-starfish-towel-with-copy-space_23-2148223762.jpg';
import blogImg4 from '../assets/Planks with the horizon in the distance _ Free Photo_files/blurred-colorful-hello-summer-background_23-2148156630.jpg';
import blogImg5 from '../assets/Planks with the horizon in the distance _ Free Photo_files/enjoy-summer-holidays-background_23-2147509589.jpg';
import blogImg6 from '../assets/Planks with the horizon in the distance _ Free Photo_files/hello-summer-background-with-sea-blurred_23-2147813054.jpg';

const blogs = [
  {
    id: 1,
    title: '10 Hidden Gems in Sinai You Must Explore',
    category: 'Adventure',
    categoryColor: '#e74c3c',
    author: 'Rahaf Adel',
    date: 'June 10, 2026',
    readTime: '6 min read',
    image: blogImg1,
    excerpt: 'Beyond the famous shores of Sharm and Dahab lies a world of untouched canyons, secret oases and ancient Bedouin trails waiting to be discovered.',
    content: [
      "The Sinai Peninsula is one of Egypt's best-kept secrets. While millions of tourists flock to its famous shores every year, the real magic lies hidden deeper — in the heart of its rugged mountains and forgotten valleys.",
      "Start your journey at the Colored Canyon, a narrow gorge where the sandstone walls glow in shades of red, yellow and purple. The best time to visit is at sunrise, when the light paints the rocks in golden hues you will never forget.",
      "Further north, the oasis of Ain Khudra sits like a mirage — a patch of green in the middle of the desert where Bedouin families have lived for centuries. Sit with them over a cup of sage tea and listen to stories of the land.",
      "For the more adventurous traveler, the mountain trails of South Sinai lead to ancient Christian monasteries, high-altitude wadis and viewpoints that feel like the edge of the world. Mount Sinai itself, best climbed before dawn, rewards you with one of the most breathtaking sunrises on the planet.",
      "The underwater world of the Gulf of Aqaba adds another dimension to Sinai's charm. The coral gardens of Blue Hole in Dahab and the pristine reefs near Nuweiba are rated among the top dive sites on Earth.",
      "Whether you are a hiker, a diver, a history lover or simply someone seeking silence — Sinai has a hidden gem waiting just for you.",
    ],
  },
  {
    id: 2,
    title: 'The Ultimate Packing Guide for Beach Trips',
    category: 'Tips & Tricks',
    categoryColor: '#3498db',
    author: 'Sara Khalil',
    date: 'May 28, 2026',
    readTime: '4 min read',
    image: blogImg2,
    excerpt: 'Pack smarter, not heavier. This guide covers everything you need — and nothing you do not — for the perfect beach holiday.',
    content: [
      "There is an art to packing for a beach trip, and it has nothing to do with squeezing in as much as possible. It is about bringing exactly what you need, and leaving behind everything that will just weigh you down.",
      "Start with the essentials: reef-safe sunscreen (SPF 50 or above), a quality rash guard, and at least two swimsuits so one can dry while you wear the other. A microfiber towel takes up almost no space and dries in minutes — it should replace your heavy cotton towel every single time.",
      "Footwear is often where people overpack. You need exactly three pairs: flip flops for the beach, comfortable walking sandals for exploring, and one pair of closed shoes for evening outings or unexpected hikes.",
      "For electronics, waterproof cases are non-negotiable. Bring a lightweight action camera if you want underwater memories, and always pack a portable charger — beach days are long and power outlets are rare.",
      "Finally, the most underrated item in any beach bag: a large lightweight tote. It serves as a beach bag, a shopping bag, and an extra carry-on all in one. Choose one in a bright color so it is easy to spot on the sand.",
      "Pack these things right, and you will wonder why you ever checked in a bag in the first place.",
    ],
  },
  {
    id: 3,
    title: 'Why Santorini is Worth Every Penny',
    category: 'Destinations',
    categoryColor: '#9b59b6',
    author: 'Nour Hassan',
    date: 'May 15, 2026',
    readTime: '5 min read',
    image: blogImg3,
    excerpt: 'Yes, it is expensive. Yes, it is crowded in August. And yes, it is still absolutely worth it — here is why Santorini earns its legendary status.',
    content: [
      "Every travel writer has a Santorini story. Mine started at 6am, standing on a cliff edge in Oia, watching the sun rise over the caldera while the island was still asleep. In that moment, every euro spent felt like a bargain.",
      "Santorini is one of those rare destinations that actually lives up to its photographs — and then exceeds them. The famous blue-domed churches, the white-washed houses cascading down volcanic cliffs, the deep blue of the Aegean below. It is all real.",
      "The food alone justifies the trip. Fresh grilled octopus, fava bean dip, tomato fritters made from the island's unique small tomatoes — paired with a glass of Assyrtiko wine from grapes grown in volcanic soil since the Bronze Age.",
      "My advice: avoid July and August if you can. Visit in May or September when the crowds thin out, prices drop by 30%, and you can actually walk through Oia without being swept along by a wave of tourists.",
      "Stay in Imerovigli rather than Oia for caldera views at half the price. Take the cable car down to the old port at sunset. Swim at Perissa's black sand beach. And never, ever miss a caldera cruise.",
      "Santorini is not cheap. But some experiences transcend budgets — and this island is one of them.",
    ],
  },
  {
    id: 4,
    title: 'Solo Travel in Bali: A First-Timer\'s Guide',
    category: 'Solo Travel',
    categoryColor: '#27ae60',
    author: 'Lina Mostafa',
    date: 'April 30, 2026',
    readTime: '7 min read',
    image: blogImg4,
    excerpt: "Bali is one of the world's most popular solo travel destinations — and for good reason. Here is everything you need to know before your first solo trip.",
    content: [
      "When I told people I was going to Bali alone, the reactions were split: half said 'amazing', the other half said 'be careful'. After three weeks solo on the island, I can tell you — it was amazing, and I was perfectly safe.",
      "Bali has one of the most welcoming solo travel cultures in the world. The Balinese people are genuinely warm and curious, and the island's infrastructure for travelers — from cheap scooter rentals to co-working cafes — makes it easy to both explore and connect.",
      "Base yourself in Canggu for your first week. It has the best balance of beach access, cafes, surf schools and a thriving community of solo travelers and digital nomads. You will make friends within your first day.",
      "Then move to Ubud for a change of pace. The spiritual heart of Bali, Ubud sits among green rice terraces and ancient temples. Rent a scooter and get lost on the back roads. Find a sunrise yoga class. Visit the Tirta Empul temple for the purification ceremony.",
      "Budget tip: eat at warungs (local family restaurants). For $2–3, you get a full plate of nasi goreng, satay and fresh coconut water. It is always better than the overpriced tourist restaurants on the main drag.",
      "Bali will challenge you, surprise you and inspire you. Go alone — you will not regret it for a single moment.",
    ],
  },
  {
    id: 5,
    title: 'The Best Underwater Spots Along the Red Sea',
    category: 'Diving',
    categoryColor: '#1abc9c',
    author: 'Rahaf Adel',
    date: 'April 12, 2026',
    readTime: '5 min read',
    image: blogImg5,
    excerpt: "The Red Sea is home to some of the world's most spectacular marine life. From Dahab's Blue Hole to Hurghada's reefs, here are the spots every diver must visit.",
    content: [
      "Egypt's Red Sea coast is a diver's paradise — warm, clear water, visibility up to 30 meters, and coral ecosystems that have been thriving for millions of years. Whether you are a beginner or an expert, there is a site that will take your breath away.",
      "The most famous site is undoubtedly the Blue Hole in Dahab — a 130-meter deep underwater sinkhole that has attracted technical divers from around the world. For recreational divers, the rim and the arch at 55 meters are spectacular. For snorkelers, the shallow coral garden above is equally stunning.",
      "In Hurghada, the Giftun Island reefs offer some of the richest marine biodiversity in Egypt. Schools of jackfish, sea turtles, moray eels and occasional reef sharks can all be spotted in a single dive. The ship wreck of the SS Thistlegorm, a few hours north, is one of the best wreck dives in the world.",
      "Sharm El Sheikh's Ras Mohammed National Park is the jewel of the Red Sea. The Shark and Yolanda reef is famous for its sheer walls dropping to over 800 meters, dense coral gardens and the famous Yolanda toilet bowls — cargo from a ship that sank here in 1980.",
      "The lesser-known sites near Nuweiba and Taba offer solitude and unspoiled reefs that most visitors to Egypt never discover. Hire a local Bedouin guide and explore the coastline by boat for an experience that feels completely off the beaten path.",
    ],
  },
  {
    id: 6,
    title: 'How to Plan a Family Trip Without Losing Your Mind',
    category: 'Family Travel',
    categoryColor: '#e67e22',
    author: 'Mona Fathy',
    date: 'March 25, 2026',
    readTime: '6 min read',
    image: blogImg6,
    excerpt: 'Family travel is rewarding, chaotic, and unforgettable. With the right planning, it can be mostly the first and last of those things.',
    content: [
      "The secret to a successful family trip is not a perfect itinerary — it is building enough flexibility into the plan to handle everything that will inevitably not go according to it.",
      "Start planning at least three months in advance for international trips. Book accommodations with kitchens or kitchenettes — the ability to prepare simple meals saves both money and the time spent negotiating with tired, hungry children in restaurants.",
      "Choose destinations wisely. The best family destinations offer a mix: something for the adults (culture, food, history), something for the kids (beach, activities, space to run around) and enough downtime for everyone to recharge.",
      "Pack a dedicated kids' bag that they can carry themselves, filled with their own entertainment: books, small toys, headphones and tablets pre-loaded with movies. Long travel days become manageable when children feel ownership over their journey.",
      "One rule that transforms family trips: commit to one 'adult activity' and one 'kids activity' per day. Parents get their museum or sunset dinner, kids get their beach time or theme park. Everyone's needs are respected.",
      "The mess, the tantrums, the forgotten sunscreen and the delayed flights — these become the stories you laugh about for years. Family travel is never perfect, but it is always worth it.",
    ],
  },
];

export default blogs;
