import img1 from '../assets/Planks with the horizon in the distance _ Free Photo_files/beach-with-clouds-birds-background_23-2147489710.jpg';
import img2 from '../assets/Planks with the horizon in the distance _ Free Photo_files/blue-ocean-landscape-with-cloudy-sky_1314-2476.jpg';
import img3 from '../assets/Planks with the horizon in the distance _ Free Photo_files/planks-with-horizon-distance_1149-1043.jpg';
import img4 from '../assets/Planks with the horizon in the distance _ Free Photo_files/defocused-beach-background_23-2147630190.jpg';
import img5 from '../assets/Planks with the horizon in the distance _ Free Photo_files/sunny-day-with-sea-background_1160-233.jpg';
import img6 from '../assets/Planks with the horizon in the distance _ Free Photo_files/scape-paradise-background_23-2147513773.jpg';
import img7 from '../assets/Planks with the horizon in the distance _ Free Photo_files/beautiful-sky-river-with-floor_1112-1127.jpg';
import img8 from '../assets/Planks with the horizon in the distance _ Free Photo_files/sea-background-with-seashore-starfishes_23-2147548857.jpg';
import img9 from '../assets/Planks with the horizon in the distance _ Free Photo_files/defocused-sea-background_23-2147671687.jpg';
import img10 from '../assets/Planks with the horizon in the distance _ Free Photo_files/blurred-sea-background_23-2147503955.jpg';

const destinations = [
  {
    id: 1,
    name: 'Sharm El Sheikh',
    country: 'Egypt',
    flag: '🇪🇬',
    category: 'egypt',
    image: img1,
    price: 299,
    rating: 4.8,
    reviews: 1243,
    description: 'A world-class diving destination at the tip of the Sinai Peninsula, with crystal-clear waters, vibrant coral reefs, and luxury resorts lining the shores of the Red Sea.',
    highlights: ['Snorkeling & Diving', 'Ras Mohammed Park', 'Naama Bay Nightlife', 'Old Market Bazaar', 'Desert Safari'],
    bestTime: 'October – April',
    duration: '5–7 days',
    weather: '25–35°C',
  },
  {
    id: 2,
    name: 'Hurghada',
    country: 'Egypt',
    flag: '🇪🇬',
    category: 'egypt',
    image: img2,
    price: 249,
    rating: 4.7,
    reviews: 987,
    description: 'A vibrant Red Sea resort city known for its sandy beaches, warm clear waters and year-round sunshine — the perfect gateway for water sports lovers.',
    highlights: ['Red Sea Diving', 'Giftun Island Trip', 'Marina Boulevard', 'Desert Quad Biking', 'Dolphin Show'],
    bestTime: 'September – May',
    duration: '4–6 days',
    weather: '22–34°C',
  },
  {
    id: 3,
    name: 'Alexandria',
    country: 'Egypt',
    flag: '🇪🇬',
    category: 'egypt',
    image: img3,
    price: 199,
    rating: 4.6,
    reviews: 756,
    description: "Egypt's pearl on the Mediterranean — a fusion of ancient ruins, colonial architecture, lively corniche walks and legendary fresh seafood culture.",
    highlights: ['Bibliotheca Alexandrina', 'Qaitbay Citadel', 'Stanley Beach', 'Montazah Palace Gardens', 'Roman Amphitheater'],
    bestTime: 'April – October',
    duration: '3–4 days',
    weather: '18–30°C',
  },
  {
    id: 4,
    name: 'Dahab',
    country: 'Egypt',
    flag: '🇪🇬',
    category: 'egypt',
    image: img4,
    price: 219,
    rating: 4.9,
    reviews: 634,
    description: "A relaxed coastal town on the Gulf of Aqaba, beloved by backpackers and divers for its legendary Blue Hole and laid-back Bedouin vibe.",
    highlights: ['Blue Hole Diving', 'Eel Garden Snorkeling', 'Bedouin Desert Camps', 'Windsurfing & Kiteboarding', 'Blue Lagoon'],
    bestTime: 'March – May, Oct – Nov',
    duration: '4–7 days',
    weather: '20–35°C',
  },
  {
    id: 5,
    name: 'Maldives',
    country: 'Maldives',
    flag: '🇲🇻',
    category: 'international',
    image: img5,
    price: 1299,
    rating: 5.0,
    reviews: 2108,
    description: "A tropical paradise of 1,200 coral islands scattered across the Indian Ocean — overwater bungalows, pristine white sand, and some of Earth's most spectacular diving.",
    highlights: ['Overwater Bungalows', 'Manta Ray Snorkeling', 'Sunset Dolphin Cruises', 'Bioluminescent Beaches', 'Whale Shark Tours'],
    bestTime: 'November – April',
    duration: '7–10 days',
    weather: '26–30°C',
  },
  {
    id: 6,
    name: 'Bali',
    country: 'Indonesia',
    flag: '🇮🇩',
    category: 'international',
    image: img6,
    price: 699,
    rating: 4.8,
    reviews: 3421,
    description: "The Island of the Gods — a harmonious blend of surf beaches, emerald rice paddies, ancient Hindu temples and a vibrant spiritual culture unlike anywhere else.",
    highlights: ['Ubud Rice Terraces', 'Tanah Lot Sunset Temple', 'Seminyak Beach Clubs', 'Mount Batur Sunrise Trek', 'Traditional Cooking Class'],
    bestTime: 'April – October',
    duration: '7–14 days',
    weather: '26–32°C',
  },
  {
    id: 7,
    name: 'Santorini',
    country: 'Greece',
    flag: '🇬🇷',
    category: 'international',
    image: img7,
    price: 899,
    rating: 4.9,
    reviews: 1876,
    description: "The iconic white-washed cliffs of Santorini rise above the deep blue Aegean Sea — a romantic island of legendary sunsets, volcanic beaches and world-class wine.",
    highlights: ['Oia Village Sunset', 'Caldera Sailing Cruise', 'Black Sand Perissa Beach', 'Local Wine Tasting', 'Akrotiri Ancient Ruins'],
    bestTime: 'April – October',
    duration: '5–7 days',
    weather: '20–30°C',
  },
  {
    id: 8,
    name: 'Phuket',
    country: 'Thailand',
    flag: '🇹🇭',
    category: 'international',
    image: img8,
    price: 599,
    rating: 4.7,
    reviews: 2654,
    description: "Thailand's largest island offers a dazzling combination of azure waters, jungle-clad hills, vibrant street food, colorful nightlife and ancient Buddhist temples.",
    highlights: ['Phi Phi Island Day Trip', 'Big Buddha Monument', 'Patong Beach', 'Phang Nga Bay Kayaking', 'Night Markets & Street Food'],
    bestTime: 'November – April',
    duration: '6–10 days',
    weather: '25–33°C',
  },
  {
    id: 9,
    name: 'Ain Sokhna',
    country: 'Egypt',
    flag: '🇪🇬',
    category: 'egypt',
    image: img9,
    price: 149,
    rating: 4.5,
    reviews: 421,
    description: "Cairo's closest escape — a peaceful Red Sea resort just 120km from the capital, with calm waters, private beach resorts and family-friendly amenities.",
    highlights: ['Private Beach Resorts', 'Jet Skiing & Water Sports', 'Coral Reef Snorkeling', 'Weekend Family Getaway', 'Seafood Restaurants'],
    bestTime: 'October – May',
    duration: '2–3 days',
    weather: '20–32°C',
  },
  {
    id: 10,
    name: 'Zanzibar',
    country: 'Tanzania',
    flag: '🇹🇿',
    category: 'international',
    image: img10,
    price: 849,
    rating: 4.8,
    reviews: 1102,
    description: "The Spice Island of the Indian Ocean — turquoise waters, powder-white beaches, labyrinthine Stone Town alleys and the most unforgettable African sunsets.",
    highlights: ['Nungwi Beach', 'Stone Town Old Quarter', 'Spice Farm Tour', 'Dolphin Watching at Kizimkazi', 'Snorkeling at Mnemba Atoll'],
    bestTime: 'June – October',
    duration: '7–10 days',
    weather: '25–32°C',
  },
];

export default destinations;
